version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  webhook-service:
    build: .
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RAZORPAY_WEBHOOK_SECRET: nkdPt8OpyM5qj33oBqEPi4qo
      PORT: 8004
    ports:
      - "8004:8004"  