services:
  webhook-service:
    build: .
    container_name: webhook-service
    restart: always
    environment:
      RABBITMQ_URL: amqp://guest:guest@dhwaniastro-rabbitmq:5672
      RAZORPAY_WEBHOOK_SECRET: nkdPt8OpyM5qj33oBqEPi4qo
      PORT: 8004
    ports:
      - "8004:8004"
    mem_limit: 512m
    cpus: 0.5
    networks:
      - dhwaniastro-net

networks:
  dhwaniastro-net:
    external: true